staging:
  adapter: redis
  url: "redis://#{ENV.fetch('REDIS_HOST', 'localhost')}:#{ENV.fetch('REDIS_PORT', 6379)}/1"

testing:
  adapter: test

production:
  adapter: redis
  url: "redis://#{ENV.fetch('REDIS_HOST', 'localhost')}:#{ENV.fetch('REDIS_PORT', 6379)}/0"
  channel_prefix: rapidx_backend_production
